import { Bunny } from "@/app/_store/bunnyStore";
import { FundBunny } from "@/app/_store/fundingStore";
import { BunnyPressureData, PressureResponse } from "@/app/personal/home/_types/interfaces";

export let DUMMY_BUNNIES: Bunny[] = [
    {
        bunny_id: "bunny-001",
        user_name: "김민준",
        bunny_name: "MinjunBunny",
        image: "/images/login/personalProfile.png",
        developer_type: "GROWTH",
        bunny_type: "A",
        position: "BACKEND",
        reliability: 92,
        current_price: 48500,
        closing_price: 47000,
        market_cap: 4850000,
        fluctuation_rate: 3.19,
        growth: 88,
        stability: 72,
        value: 80,
        popularity: 75,
        balance: 70,
        badges: ["KAKAO", "TOSS"],
        like_count: 134,
        ai_review: "성장 가능성이 높은 백엔드 개발자입니다.",
        created_at: "2026-04-01T09:00:00",
    },
    {
        bunny_id: "bunny-002",
        user_name: "이서연",
        bunny_name: "SeoyeonBunny",
        image: "/images/login/personalProfile.png",
        developer_type: "STABLE",
        bunny_type: "B",
        position: "FRONTEND",
        reliability: 88,
        current_price: 35200,
        closing_price: 36000,
        market_cap: 3520000,
        fluctuation_rate: -2.22,
        growth: 65,
        stability: 91,
        value: 78,
        popularity: 82,
        balance: 85,
        badges: ["NAVER", "LINE", "SAMSUNG"],
        like_count: 209,
        ai_review: "안정적인 프론트엔드 전문가입니다.",
        created_at: "2026-04-01T08:30:00",
    },
    {
        bunny_id: "bunny-003",
        user_name: "박지호",
        bunny_name: "JihoBunny",
        image: "/images/login/personalProfile.png",
        developer_type: "VALUE",
        bunny_type: "A",
        position: "FULLSTACK",
        reliability: 95,
        current_price: 72000,
        closing_price: 70000,
        market_cap: 7200000,
        fluctuation_rate: 2.86,
        growth: 77,
        stability: 85,
        value: 94,
        popularity: 68,
        balance: 80,
        badges: ["KAKAO", "WOOWAHAN", "COUPANG"],
        like_count: 317,
        ai_review: "높은 가치를 지닌 풀스택 개발자입니다.",
        created_at: "2026-04-01T10:15:00",
    },
    {
        bunny_id: "bunny-004",
        user_name: "최예린",
        bunny_name: "YerinBunny",
        image: "/images/login/personalProfile.png",
        developer_type: "POPULAR",
        bunny_type: "C",
        position: "FRONTEND",
        reliability: 80,
        current_price: 28900,
        closing_price: 27500,
        market_cap: 2890000,
        fluctuation_rate: 5.09,
        growth: 82,
        stability: 60,
        value: 70,
        popularity: 96,
        balance: 65,
        badges: ["DAANGN", "TOSS"],
        like_count: 442,
        ai_review: "높은 인기를 자랑하는 프론트엔드 개발자입니다.",
        created_at: "2026-04-01T07:45:00",
    },
    {
        bunny_id: "bunny-005",
        user_name: "정우성",
        bunny_name: "WoosungBunny",
        image: "/images/login/personalProfile.png",
        developer_type: "BALANCE",
        bunny_type: "B",
        position: "BACKEND",
        reliability: 90,
        current_price: 53100,
        closing_price: 54000,
        market_cap: 5310000,
        fluctuation_rate: -1.67,
        growth: 78,
        stability: 82,
        value: 80,
        popularity: 79,
        balance: 93,
        badges: ["SK", "LG", "HYUNDAI"],
        like_count: 188,
        ai_review: "균형 잡힌 역량을 보유한 백엔드 개발자입니다.",
        created_at: "2026-04-01T11:00:00",
    },
    {
        bunny_id: "bunny-006",
        user_name: "한지수",
        bunny_name: "JisuBunny",
        image: "/images/login/personalProfile.png",
        developer_type: "GROWTH",
        bunny_type: "A",
        position: "FULLSTACK",
        reliability: 85,
        current_price: 41600,
        closing_price: 40000,
        market_cap: 4160000,
        fluctuation_rate: 4.0,
        growth: 91,
        stability: 68,
        value: 75,
        popularity: 80,
        balance: 72,
        badges: ["SHINHAN", "TOSS"],
        like_count: 256,
        ai_review: "빠르게 성장하는 풀스택 개발자입니다.",
        created_at: "2026-04-01T06:30:00",
    },
    {
        bunny_id: "bunny-007",
        user_name: "윤도현",
        bunny_name: "DohyunBunny",
        image: "/images/login/personalProfile.png",
        developer_type: "STABLE",
        bunny_type: "C",
        position: "BACKEND",
        reliability: 94,
        current_price: 62400,
        closing_price: 62400,
        market_cap: 6240000,
        fluctuation_rate: 0.0,
        growth: 60,
        stability: 95,
        value: 85,
        popularity: 70,
        balance: 88,
        badges: ["SAMSUNG", "LG", "NAVER"],
        like_count: 173,
        ai_review: "변동성 없이 안정적인 백엔드 전문가입니다.",
        created_at: "2026-04-01T12:00:00",
    },
    {
        bunny_id: "bunny-008",
        user_name: "임수아",
        bunny_name: "SuaBunny",
        image: "/images/login/personalProfile.png",
        developer_type: "VALUE",
        bunny_type: "B",
        position: "FRONTEND",
        reliability: 87,
        current_price: 39800,
        closing_price: 38200,
        market_cap: 3980000,
        fluctuation_rate: 4.19,
        growth: 72,
        stability: 78,
        value: 90,
        popularity: 76,
        balance: 74,
        badges: ["KAKAO", "LINE"],
        like_count: 299,
        ai_review: "내재 가치가 높은 프론트엔드 개발자입니다.",
        created_at: "2026-04-01T08:00:00",
    },
    {
        bunny_id: "bunny-009",
        user_name: "강현우",
        bunny_name: "HyunwuBunny",
        image: "/images/login/personalProfile.png",
        developer_type: "POPULAR",
        bunny_type: "A",
        position: "FULLSTACK",
        reliability: 83,
        current_price: 31500,
        closing_price: 33000,
        market_cap: 3150000,
        fluctuation_rate: -4.55,
        growth: 80,
        stability: 65,
        value: 72,
        popularity: 94,
        balance: 68,
        badges: ["WOOWAHAN", "COUPANG", "DAANGN"],
        like_count: 521,
        ai_review: "커뮤니티에서 인기 있는 풀스택 개발자입니다.",
        created_at: "2026-04-01T09:30:00",
    },
    {
        bunny_id: "bunny-010",
        user_name: "오지영",
        bunny_name: "JiyoungBunny",
        image: "/images/login/personalProfile.png",
        developer_type: "BASIC",
        bunny_type: "C",
        position: "BACKEND",
        reliability: 78,
        current_price: 22100,
        closing_price: 21000,
        market_cap: 2210000,
        fluctuation_rate: 5.24,
        growth: 70,
        stability: 70,
        value: 68,
        popularity: 72,
        balance: 70,
        badges: ["SK"],
        like_count: 95,
        ai_review: "탄탄한 기본기를 갖춘 백엔드 개발자입니다.",
        created_at: "2026-04-01T13:00:00",
    },
    {
        bunny_id: "bunny-011",
        user_name: "신재원",
        bunny_name: "JaewonBunny",
        image: "/images/login/personalProfile.png",
        developer_type: "GROWTH",
        bunny_type: "B",
        position: "FRONTEND",
        reliability: 86,
        current_price: 44700,
        closing_price: 43000,
        market_cap: 4470000,
        fluctuation_rate: 3.95,
        growth: 89,
        stability: 71,
        value: 76,
        popularity: 83,
        balance: 73,
        badges: ["TOSS", "KAKAO", "NAVER"],
        like_count: 368,
        ai_review: "트렌드를 선도하는 프론트엔드 개발자입니다.",
        created_at: "2026-04-01T10:45:00",
    },
    {
        bunny_id: "bunny-012",
        user_name: "류하은",
        bunny_name: "HaeunBunny",
        image: "/images/login/personalProfile.png",
        developer_type: "BALANCE",
        bunny_type: "A",
        position: "FULLSTACK",
        reliability: 91,
        current_price: 58300,
        closing_price: 57000,
        market_cap: 5830000,
        fluctuation_rate: 2.28,
        growth: 81,
        stability: 83,
        value: 82,
        popularity: 80,
        balance: 91,
        badges: ["SHINHAN", "HYUNDAI", "SAMSUNG"],
        like_count: 234,
        ai_review: "전방위 균형 잡힌 풀스택 개발자입니다.",
        created_at: "2026-04-01T07:00:00",
    },
    {
        bunny_id: "bunny-013",
        user_name: "배성현",
        bunny_name: "SeonghyunBunny",
        image: "/images/login/personalProfile.png",
        developer_type: "VALUE",
        bunny_type: "A",
        position: "BACKEND",
        reliability: 93,
        current_price: 67800,
        closing_price: 65000,
        market_cap: 6780000,
        fluctuation_rate: 4.31,
        growth: 74,
        stability: 88,
        value: 95,
        popularity: 66,
        balance: 79,
        badges: ["KAKAO", "COUPANG"],
        like_count: 278,
        ai_review: "탄탄한 아키텍처 설계 능력을 갖춘 백엔드 개발자입니다.",
        created_at: "2026-04-01T08:20:00",
    },
    {
        bunny_id: "bunny-014",
        user_name: "전민아",
        bunny_name: "MinaBunny",
        image: "/images/login/personalProfile.png",
        developer_type: "POPULAR",
        bunny_type: "B",
        position: "FRONTEND",
        reliability: 81,
        current_price: 26400,
        closing_price: 27200,
        market_cap: 2640000,
        fluctuation_rate: -2.94,
        growth: 85,
        stability: 62,
        value: 71,
        popularity: 97,
        balance: 67,
        badges: ["DAANGN", "NAVER", "TOSS"],
        like_count: 603,
        ai_review: "UI/UX 감각이 뛰어난 인기 프론트엔드 개발자입니다.",
        created_at: "2026-04-01T09:10:00",
    },
    {
        bunny_id: "bunny-015",
        user_name: "홍준혁",
        bunny_name: "JunhyukBunny",
        image: "/images/login/personalProfile.png",
        developer_type: "GROWTH",
        bunny_type: "C",
        position: "FULLSTACK",
        reliability: 84,
        current_price: 38100,
        closing_price: 36500,
        market_cap: 3810000,
        fluctuation_rate: 4.38,
        growth: 93,
        stability: 64,
        value: 73,
        popularity: 78,
        balance: 70,
        badges: ["WOOWAHAN", "LINE"],
        like_count: 312,
        ai_review: "빠른 학습력으로 성장 중인 풀스택 개발자입니다.",
        created_at: "2026-04-01T10:00:00",
    },
    {
        bunny_id: "bunny-016",
        user_name: "문소희",
        bunny_name: "SoheeBunny",
        image: "/images/login/personalProfile.png",
        developer_type: "STABLE",
        bunny_type: "A",
        position: "FRONTEND",
        reliability: 96,
        current_price: 71500,
        closing_price: 71000,
        market_cap: 7150000,
        fluctuation_rate: 0.70,
        growth: 58,
        stability: 97,
        value: 88,
        popularity: 73,
        balance: 90,
        badges: ["SAMSUNG", "NAVER", "KAKAO"],
        like_count: 197,
        ai_review: "극도의 안정성을 자랑하는 시니어 프론트엔드 개발자입니다.",
        created_at: "2026-04-01T06:00:00",
    },
    {
        bunny_id: "bunny-017",
        user_name: "서동훈",
        bunny_name: "DonghunBunny",
        image: "/images/login/personalProfile.png",
        developer_type: "BALANCE",
        bunny_type: "B",
        position: "BACKEND",
        reliability: 89,
        current_price: 49600,
        closing_price: 48800,
        market_cap: 4960000,
        fluctuation_rate: 1.64,
        growth: 80,
        stability: 84,
        value: 81,
        popularity: 77,
        balance: 94,
        badges: ["SK", "HYUNDAI"],
        like_count: 221,
        ai_review: "모든 역량이 고르게 발달한 균형형 백엔드 개발자입니다.",
        created_at: "2026-04-01T11:30:00",
    },
    {
        bunny_id: "bunny-018",
        user_name: "노채원",
        bunny_name: "ChaewonBunny",
        image: "/images/login/personalProfile.png",
        developer_type: "GROWTH",
        bunny_type: "A",
        position: "FRONTEND",
        reliability: 82,
        current_price: 33700,
        closing_price: 31900,
        market_cap: 3370000,
        fluctuation_rate: 5.64,
        growth: 94,
        stability: 60,
        value: 74,
        popularity: 88,
        balance: 69,
        badges: ["TOSS", "KAKAO"],
        like_count: 455,
        ai_review: "폭발적인 성장세를 보이는 신예 프론트엔드 개발자입니다.",
        created_at: "2026-04-01T12:30:00",
    },
    {
        bunny_id: "bunny-019",
        user_name: "황인석",
        bunny_name: "InseokBunny",
        image: "/images/login/personalProfile.png",
        developer_type: "VALUE",
        bunny_type: "C",
        position: "FULLSTACK",
        reliability: 90,
        current_price: 55900,
        closing_price: 54500,
        market_cap: 5590000,
        fluctuation_rate: 2.57,
        growth: 76,
        stability: 86,
        value: 92,
        popularity: 69,
        balance: 82,
        badges: ["WOOWAHAN", "COUPANG", "LG"],
        like_count: 344,
        ai_review: "장기적 관점의 가치 투자형 풀스택 개발자입니다.",
        created_at: "2026-04-01T07:30:00",
    },
    {
        bunny_id: "bunny-020",
        user_name: "김태양",
        bunny_name: "TaeyangBunny",
        image: "/images/login/personalProfile.png",
        developer_type: "BASIC",
        bunny_type: "B",
        position: "BACKEND",
        reliability: 76,
        current_price: 19800,
        closing_price: 20300,
        market_cap: 1980000,
        fluctuation_rate: -2.46,
        growth: 66,
        stability: 72,
        value: 65,
        popularity: 70,
        balance: 68,
        badges: ["SK"],
        like_count: 87,
        ai_review: "성실함으로 꾸준히 성장하는 주니어 백엔드 개발자입니다.",
        created_at: "2026-04-01T13:30:00",
    },
    {
        bunny_id: "bunny-021",
        user_name: "이하늘",
        bunny_name: "HaneulBunny",
        image: "/images/login/personalProfile.png",
        developer_type: "POPULAR",
        bunny_type: "A",
        position: "FRONTEND",
        reliability: 85,
        current_price: 42300,
        closing_price: 40100,
        market_cap: 4230000,
        fluctuation_rate: 5.49,
        growth: 87,
        stability: 63,
        value: 77,
        popularity: 98,
        balance: 71,
        badges: ["LINE", "NAVER", "DAANGN"],
        like_count: 711,
        ai_review: "커뮤니티 내 최고 인기를 구가하는 프론트엔드 개발자입니다.",
        created_at: "2026-04-01T09:50:00",
    },
    {
        bunny_id: "bunny-022",
        user_name: "조민찬",
        bunny_name: "MinchangBunny",
        image: "/images/login/personalProfile.png",
        developer_type: "STABLE",
        bunny_type: "B",
        position: "FULLSTACK",
        reliability: 92,
        current_price: 60200,
        closing_price: 59800,
        market_cap: 6020000,
        fluctuation_rate: 0.67,
        growth: 62,
        stability: 93,
        value: 86,
        popularity: 74,
        balance: 87,
        badges: ["SHINHAN", "SAMSUNG", "KAKAO"],
        like_count: 163,
        ai_review: "변동 없이 꾸준한 퍼포먼스를 내는 풀스택 개발자입니다.",
        created_at: "2026-04-01T05:30:00",
    },
];

export const DUMMY_RABBIT_INDEX = 72;

export const DUMMY_PRESSURE: PressureResponse = {
    buy_top5: [
        { bunny_id: "bunny-003", bunny_name: "JihoBunny",    date: "2026-04-01", pressure: 8421 },
        { bunny_id: "bunny-001", bunny_name: "MinjunBunny",  date: "2026-04-01", pressure: 7354 },
        { bunny_id: "bunny-011", bunny_name: "JaewonBunny",  date: "2026-04-01", pressure: 6890 },
        { bunny_id: "bunny-005", bunny_name: "WoosungBunny", date: "2026-04-01", pressure: 5612 },
        { bunny_id: "bunny-012", bunny_name: "HaeunBunny",   date: "2026-04-01", pressure: 4977 },
    ],
    sell_top5: [
        { bunny_id: "bunny-009", bunny_name: "HyunwuBunny",  date: "2026-04-01", pressure: 7103 },
        { bunny_id: "bunny-004", bunny_name: "YerinBunny",   date: "2026-04-01", pressure: 6248 },
        { bunny_id: "bunny-002", bunny_name: "SeoyeonBunny", date: "2026-04-01", pressure: 5531 },
        { bunny_id: "bunny-007", bunny_name: "DohyunBunny",  date: "2026-04-01", pressure: 4820 },
        { bunny_id: "bunny-006", bunny_name: "JisuBunny",    date: "2026-04-01", pressure: 3674 },
    ],
};

// ────────────────────────────────────────────────
// Spec 타입 (BunnySpec 컴포넌트의 내부 인터페이스와 동일)
// ────────────────────────────────────────────────
interface SpecLink       { sns_id: string; url: string; type: string; favicon: string; }
interface SpecCert       { certification_id: string; certificate_url: string; name: string; ca: string; cdate: string; }
interface SpecCareer     { career_id: string; company_name: string; status: string; position: string; start_date: string; end_date: string | null; certificate_url: string; }
interface SpecEducation  { education_id: string; school_name: string; status: string; major: string; start_date: string; end_date: string; certificate_url: string; }
export interface BunnySpec {
    name: string; birthdate: string; email: string; phone: string;
    image: string; resume: string; position: string;
    link: SpecLink[]; skill: string[];
    certification: SpecCert[]; career: SpecCareer[]; education: SpecEducation[];
    ai_review: string;
}

export const DUMMY_SPECS: Record<string, BunnySpec> = {
    MinjunBunny: {
        name: "김민준", birthdate: "1995-03-12", email: "minjun.kim@kakao.com",
        phone: "010-1234-5678", image: "/images/login/personalProfile.png", resume: "",
        position: "BACKEND",
        link: [{ sns_id: "l1", url: "https://github.com/minjun-kim", type: "github", favicon: "" }],
        skill: ["Java", "Spring Boot", "Kotlin", "MySQL", "Redis", "Docker"],
        education: [{ education_id: "e1", school_name: "KAIST", status: "졸업", major: "컴퓨터공학", start_date: "2014-03-01", end_date: "2018-02-28", certificate_url: "" }],
        career: [
            { career_id: "c1", company_name: "카카오", status: "재직중", position: "백엔드 엔지니어", start_date: "2020-07-01", end_date: null, certificate_url: "" },
            { career_id: "c2", company_name: "라인", status: "퇴직", position: "서버 개발자", start_date: "2018-03-01", end_date: "2020-06-30", certificate_url: "" },
        ],
        certification: [
            { certification_id: "cert1", name: "정보처리기사", ca: "한국산업인력공단", cdate: "2018-05-15", certificate_url: "" },
            { certification_id: "cert2", name: "AWS Solutions Architect", ca: "Amazon", cdate: "2021-11-10", certificate_url: "" },
        ],
        ai_review: "성장 가능성이 높은 백엔드 개발자입니다.",
    },
    SeoyeonBunny: {
        name: "이서연", birthdate: "1997-07-25", email: "seoyeon.lee@naver.com",
        phone: "010-2345-6789", image: "/images/login/personalProfile.png", resume: "",
        position: "FRONTEND",
        link: [{ sns_id: "l2", url: "https://github.com/seoyeon-lee", type: "github", favicon: "" }],
        skill: ["React", "TypeScript", "Next.js", "Styled-components", "Figma"],
        education: [{ education_id: "e2", school_name: "연세대학교", status: "졸업", major: "정보시스템학", start_date: "2016-03-01", end_date: "2020-02-28", certificate_url: "" }],
        career: [
            { career_id: "c3", company_name: "네이버", status: "재직중", position: "프론트엔드 개발자", start_date: "2021-01-04", end_date: null, certificate_url: "" },
        ],
        certification: [
            { certification_id: "cert3", name: "정보처리기사", ca: "한국산업인력공단", cdate: "2020-06-20", certificate_url: "" },
        ],
        ai_review: "안정적인 프론트엔드 전문가입니다.",
    },
    JihoBunny: {
        name: "박지호", birthdate: "1993-11-05", email: "jiho.park@woowahan.com",
        phone: "010-3456-7890", image: "/images/login/personalProfile.png", resume: "",
        position: "FULLSTACK",
        link: [
            { sns_id: "l3", url: "https://github.com/jiho-park", type: "github", favicon: "" },
            { sns_id: "l4", url: "https://jiho.dev", type: "blog", favicon: "" },
        ],
        skill: ["React", "Node.js", "Spring Boot", "PostgreSQL", "Kubernetes", "AWS"],
        education: [{ education_id: "e3", school_name: "서울대학교", status: "졸업", major: "컴퓨터공학부", start_date: "2012-03-01", end_date: "2016-02-29", certificate_url: "" }],
        career: [
            { career_id: "c5", company_name: "우아한형제들", status: "재직중", position: "풀스택 개발자", start_date: "2019-04-01", end_date: null, certificate_url: "" },
            { career_id: "c6", company_name: "쿠팡", status: "퇴직", position: "백엔드 개발자", start_date: "2016-03-01", end_date: "2019-03-31", certificate_url: "" },
        ],
        certification: [
            { certification_id: "cert5", name: "AWS Solutions Architect Professional", ca: "Amazon", cdate: "2022-03-15", certificate_url: "" },
            { certification_id: "cert6", name: "CKA (Kubernetes)", ca: "CNCF", cdate: "2023-01-20", certificate_url: "" },
        ],
        ai_review: "높은 가치를 지닌 풀스택 개발자입니다.",
    },
    YerinBunny: {
        name: "최예린", birthdate: "1999-02-14", email: "yerin.choi@daangn.com",
        phone: "010-4567-8901", image: "/images/login/personalProfile.png", resume: "",
        position: "FRONTEND",
        link: [{ sns_id: "l5", url: "https://github.com/yerin-choi", type: "github", favicon: "" }],
        skill: ["Vue.js", "React", "JavaScript", "CSS", "Figma", "Storybook"],
        education: [{ education_id: "e4", school_name: "홍익대학교", status: "졸업", major: "컴퓨터공학", start_date: "2018-03-01", end_date: "2022-02-28", certificate_url: "" }],
        career: [
            { career_id: "c7", company_name: "당근마켓", status: "재직중", position: "UI 개발자", start_date: "2022-07-01", end_date: null, certificate_url: "" },
        ],
        certification: [
            { certification_id: "cert7", name: "정보처리기사", ca: "한국산업인력공단", cdate: "2022-05-01", certificate_url: "" },
        ],
        ai_review: "높은 인기를 자랑하는 프론트엔드 개발자입니다.",
    },
    WoosungBunny: {
        name: "정우성", birthdate: "1994-09-30", email: "woosung.jung@sk.com",
        phone: "010-5678-9012", image: "/images/login/personalProfile.png", resume: "",
        position: "BACKEND",
        link: [{ sns_id: "l6", url: "https://github.com/woosung-jung", type: "github", favicon: "" }],
        skill: ["Go", "Rust", "gRPC", "Kafka", "MongoDB", "Terraform"],
        education: [{ education_id: "e5", school_name: "포항공과대학교", status: "졸업", major: "전산학", start_date: "2013-03-01", end_date: "2017-02-28", certificate_url: "" }],
        career: [
            { career_id: "c9", company_name: "SK텔레콤", status: "재직중", position: "인프라 엔지니어", start_date: "2020-01-06", end_date: null, certificate_url: "" },
            { career_id: "c10", company_name: "LG CNS", status: "퇴직", position: "백엔드 개발자", start_date: "2017-03-01", end_date: "2019-12-31", certificate_url: "" },
        ],
        certification: [
            { certification_id: "cert9", name: "정보처리기사", ca: "한국산업인력공단", cdate: "2017-06-10", certificate_url: "" },
            { certification_id: "cert10", name: "GCP Professional Cloud Architect", ca: "Google", cdate: "2022-08-05", certificate_url: "" },
        ],
        ai_review: "균형 잡힌 역량을 보유한 백엔드 개발자입니다.",
    },
    JisuBunny: {
        name: "한지수", birthdate: "1998-05-18", email: "jisu.han@toss.im",
        phone: "010-6789-0123", image: "/images/login/personalProfile.png", resume: "",
        position: "FULLSTACK",
        link: [{ sns_id: "l7", url: "https://github.com/jisu-han", type: "github", favicon: "" }],
        skill: ["React", "Node.js", "TypeScript", "GraphQL", "PostgreSQL"],
        education: [{ education_id: "e6", school_name: "성균관대학교", status: "졸업", major: "소프트웨어학", start_date: "2017-03-01", end_date: "2021-02-28", certificate_url: "" }],
        career: [
            { career_id: "c11", company_name: "토스", status: "재직중", position: "풀스택 개발자", start_date: "2021-08-02", end_date: null, certificate_url: "" },
        ],
        certification: [
            { certification_id: "cert11", name: "정보처리기사", ca: "한국산업인력공단", cdate: "2021-04-15", certificate_url: "" },
        ],
        ai_review: "빠르게 성장하는 풀스택 개발자입니다.",
    },
    DohyunBunny: {
        name: "윤도현", birthdate: "1992-12-01", email: "dohyun.yoon@samsung.com",
        phone: "010-7890-1234", image: "/images/login/personalProfile.png", resume: "",
        position: "BACKEND",
        link: [{ sns_id: "l8", url: "https://github.com/dohyun-yoon", type: "github", favicon: "" }],
        skill: ["C++", "Java", "Python", "Spark", "Hadoop", "Airflow"],
        education: [
            { education_id: "e7", school_name: "한국과학기술원(KAIST)", status: "석사졸업", major: "전산학부", start_date: "2014-03-01", end_date: "2016-02-29", certificate_url: "" },
            { education_id: "e8", school_name: "KAIST", status: "학사졸업", major: "전산학부", start_date: "2010-03-01", end_date: "2014-02-28", certificate_url: "" },
        ],
        career: [
            { career_id: "c13", company_name: "삼성SDS", status: "재직중", position: "데이터 엔지니어", start_date: "2016-03-01", end_date: null, certificate_url: "" },
        ],
        certification: [
            { certification_id: "cert13", name: "빅데이터분석기사", ca: "한국데이터산업진흥원", cdate: "2020-12-18", certificate_url: "" },
            { certification_id: "cert14", name: "정보처리기사", ca: "한국산업인력공단", cdate: "2016-05-20", certificate_url: "" },
        ],
        ai_review: "변동성 없이 안정적인 백엔드 전문가입니다.",
    },
    SuaBunny: {
        name: "임수아", birthdate: "1996-08-22", email: "sua.lim@kakao.com",
        phone: "010-8901-2345", image: "/images/login/personalProfile.png", resume: "",
        position: "FRONTEND",
        link: [
            { sns_id: "l9", url: "https://github.com/sua-lim", type: "github", favicon: "" },
            { sns_id: "l10", url: "https://sua.design", type: "portfolio", favicon: "" },
        ],
        skill: ["React", "TypeScript", "Three.js", "WebGL", "GSAP", "Figma"],
        education: [{ education_id: "e9", school_name: "이화여자대학교", status: "졸업", major: "컴퓨터공학", start_date: "2015-03-01", end_date: "2019-02-28", certificate_url: "" }],
        career: [
            { career_id: "c15", company_name: "카카오", status: "재직중", position: "프론트엔드 개발자", start_date: "2021-03-02", end_date: null, certificate_url: "" },
            { career_id: "c16", company_name: "라인", status: "퇴직", position: "UI 엔지니어", start_date: "2019-03-04", end_date: "2021-02-26", certificate_url: "" },
        ],
        certification: [
            { certification_id: "cert15", name: "정보처리기사", ca: "한국산업인력공단", cdate: "2019-05-25", certificate_url: "" },
        ],
        ai_review: "내재 가치가 높은 프론트엔드 개발자입니다.",
    },
    HyunwuBunny: {
        name: "강현우", birthdate: "1995-01-07", email: "hyunwu.kang@coupang.com",
        phone: "010-9012-3456", image: "/images/login/personalProfile.png", resume: "",
        position: "FULLSTACK",
        link: [{ sns_id: "l11", url: "https://github.com/hyunwu-kang", type: "github", favicon: "" }],
        skill: ["Python", "Django", "React", "Redis", "Elasticsearch", "AWS"],
        education: [{ education_id: "e10", school_name: "고려대학교", status: "졸업", major: "정보보호학부", start_date: "2014-03-01", end_date: "2018-02-28", certificate_url: "" }],
        career: [
            { career_id: "c17", company_name: "쿠팡", status: "재직중", position: "풀스택 개발자", start_date: "2020-09-01", end_date: null, certificate_url: "" },
            { career_id: "c18", company_name: "당근마켓", status: "퇴직", position: "백엔드 개발자", start_date: "2018-03-05", end_date: "2020-08-31", certificate_url: "" },
        ],
        certification: [
            { certification_id: "cert17", name: "정보보안기사", ca: "한국인터넷진흥원", cdate: "2019-09-14", certificate_url: "" },
            { certification_id: "cert18", name: "AWS Solutions Architect", ca: "Amazon", cdate: "2021-04-22", certificate_url: "" },
        ],
        ai_review: "커뮤니티에서 인기 있는 풀스택 개발자입니다.",
    },
    JiyoungBunny: {
        name: "오지영", birthdate: "2000-04-19", email: "jiyoung.oh@sk.com",
        phone: "010-0123-4567", image: "/images/login/personalProfile.png", resume: "",
        position: "BACKEND",
        link: [{ sns_id: "l12", url: "https://github.com/jiyoung-oh", type: "github", favicon: "" }],
        skill: ["Java", "Spring", "JPA", "MySQL", "JUnit"],
        education: [{ education_id: "e11", school_name: "한양대학교", status: "재학중", major: "컴퓨터소프트웨어학부", start_date: "2019-03-01", end_date: "2023-02-28", certificate_url: "" }],
        career: [
            { career_id: "c19", company_name: "SK하이닉스", status: "재직중", position: "신입 백엔드 개발자", start_date: "2023-07-03", end_date: null, certificate_url: "" },
        ],
        certification: [
            { certification_id: "cert19", name: "정보처리기사", ca: "한국산업인력공단", cdate: "2023-03-10", certificate_url: "" },
        ],
        ai_review: "탄탄한 기본기를 갖춘 백엔드 개발자입니다.",
    },
    JaewonBunny: {
        name: "신재원", birthdate: "1996-06-11", email: "jaewon.shin@toss.im",
        phone: "010-1357-2468", image: "/images/login/personalProfile.png", resume: "",
        position: "FRONTEND",
        link: [
            { sns_id: "l13", url: "https://github.com/jaewon-shin", type: "github", favicon: "" },
            { sns_id: "l14", url: "https://jaewon.dev", type: "blog", favicon: "" },
        ],
        skill: ["React", "TypeScript", "Next.js", "Zustand", "TailwindCSS", "Jest"],
        education: [{ education_id: "e12", school_name: "서강대학교", status: "졸업", major: "컴퓨터공학과", start_date: "2015-03-01", end_date: "2019-02-28", certificate_url: "" }],
        career: [
            { career_id: "c21", company_name: "토스", status: "재직중", position: "프론트엔드 개발자", start_date: "2022-01-10", end_date: null, certificate_url: "" },
            { career_id: "c22", company_name: "네이버", status: "퇴직", position: "웹 개발자", start_date: "2019-03-04", end_date: "2021-12-31", certificate_url: "" },
        ],
        certification: [
            { certification_id: "cert21", name: "정보처리기사", ca: "한국산업인력공단", cdate: "2019-06-08", certificate_url: "" },
            { certification_id: "cert22", name: "Google UX Design Certificate", ca: "Google", cdate: "2022-09-30", certificate_url: "" },
        ],
        ai_review: "트렌드를 선도하는 프론트엔드 개발자입니다.",
    },
    HaeunBunny: {
        name: "류하은", birthdate: "1994-10-28", email: "haeun.ryu@hyundai.com",
        phone: "010-2468-1357", image: "/images/login/personalProfile.png", resume: "",
        position: "FULLSTACK",
        link: [{ sns_id: "l15", url: "https://github.com/haeun-ryu", type: "github", favicon: "" }],
        skill: ["Java", "React", "Spring Cloud", "MSA", "Kafka", "Docker", "Kubernetes"],
        education: [
            { education_id: "e13", school_name: "서울대학교", status: "석사졸업", major: "컴퓨터공학부", start_date: "2016-03-01", end_date: "2018-02-28", certificate_url: "" },
            { education_id: "e14", school_name: "서울대학교", status: "학사졸업", major: "컴퓨터공학부", start_date: "2012-03-01", end_date: "2016-02-29", certificate_url: "" },
        ],
        career: [
            { career_id: "c23", company_name: "현대자동차", status: "재직중", position: "시니어 풀스택 개발자", start_date: "2020-05-04", end_date: null, certificate_url: "" },
            { career_id: "c24", company_name: "신한은행", status: "퇴직", position: "백엔드 개발자", start_date: "2018-03-05", end_date: "2020-04-30", certificate_url: "" },
        ],
        certification: [
            { certification_id: "cert23", name: "정보처리기사", ca: "한국산업인력공단", cdate: "2016-05-28", certificate_url: "" },
            { certification_id: "cert24", name: "AWS DevOps Engineer Professional", ca: "Amazon", cdate: "2023-02-14", certificate_url: "" },
            { certification_id: "cert25", name: "CKA (Kubernetes)", ca: "CNCF", cdate: "2022-11-03", certificate_url: "" },
        ],
        ai_review: "전방위 균형 잡힌 풀스택 개발자입니다.",
    },
};

export const DUMMY_FUND_BUNNIES: FundBunny[] = [
    {
        fund_bunny_id: "fund-001",
        bunny_name: "JiyoungBunny",
        image: "/images/login/personalProfile.png",
        bunny_type: "C",
        target_bny: 10000,
        collected_bny: 9200,
        remaining_bny: 800,
        created_at: "2026-03-25T09:00:00",
        end_at: "2026-04-02T10:00:00",
    },
    {
        fund_bunny_id: "fund-002",
        bunny_name: "YerinBunny",
        image: "/images/login/personalProfile.png",
        bunny_type: "B",
        target_bny: 15000,
        collected_bny: 14100,
        remaining_bny: 900,
        created_at: "2026-03-20T09:00:00",
        end_at: "2026-04-02T18:00:00",
    },
    {
        fund_bunny_id: "fund-003",
        bunny_name: "SuaBunny",
        image: "/images/login/personalProfile.png",
        bunny_type: "A",
        target_bny: 20000,
        collected_bny: 18500,
        remaining_bny: 1500,
        created_at: "2026-03-15T09:00:00",
        end_at: "2026-04-02T23:00:00",
    },
    {
        fund_bunny_id: "fund-004",
        bunny_name: "JisuBunny",
        image: "/images/login/personalProfile.png",
        bunny_type: "B",
        target_bny: 12000,
        collected_bny: 5400,
        remaining_bny: 6600,
        created_at: "2026-03-28T09:00:00",
        end_at: "2026-04-15T23:59:59",
    },
    {
        fund_bunny_id: "fund-005",
        bunny_name: "DohyunBunny",
        image: "/images/login/personalProfile.png",
        bunny_type: "A",
        target_bny: 25000,
        collected_bny: 8000,
        remaining_bny: 17000,
        created_at: "2026-03-30T09:00:00",
        end_at: "2026-04-20T23:59:59",
    },
    {
        fund_bunny_id: "fund-006",
        bunny_name: "WoosungBunny",
        image: "/images/login/personalProfile.png",
        bunny_type: "B",
        target_bny: 18000,
        collected_bny: 3200,
        remaining_bny: 14800,
        created_at: "2026-04-01T09:00:00",
        end_at: "2026-04-30T23:59:59",
    },
];

// DUMMY_BUNNIES 원본을 직접 수정하는 함수.
// 스토어에서 이 함수를 호출하면 re-fetch 시에도 변경값이 유지됩니다.
export function updateDummyBunny(bunnyName: string, fields: Partial<Bunny>) {
    DUMMY_BUNNIES = DUMMY_BUNNIES.map((bunny) =>
        bunny.bunny_name === bunnyName ? { ...bunny, ...fields } : bunny
    );
}
